name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Publish Module to PowerShell Gallery
        env:
          PS_GALLERY_KEY: ${{secrets.PS_GALLERY_KEY}}
          RELEASE_NOTES: ""
          RELEASE_VERSION: "0.0.${{ github.run_number }}"
        run: .github\workflows\publish.ps1
        shell: pwsh
